version: '3.8'

services:
  db:
    image: postgres
    container_name: template_engine_db
    environment:
      POSTGRES_DB: template_engine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql

  redis:
    image: redis
    container_name: template_engine_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: